### PR TITLE
Add API for main thread deallocation of classes

### PR DESCRIPTION
**Pull request by maicki**
This PR add's a new API to let classes define if objects of that class need to be deallocated on main. Therefore we create the `ASRequiringMainThreadDeallocating` protocol that classes can conform to.

As we add some overhead for checking `conformsToProtocol` as well as `ASClassRequiresMainThreadDeallocation` is a hot path, I added a generic LRUCache to cache main thread deallocation of classes. The LRUCache in general could be handy in other places too as in comparison to NSURLCache it can also have support for primitive types so it could save us boxing / unboxing cost.

It is not ready for merge yet as it needs to be cleanup, but I would like to start a conversation if we would like to go forward with this approach.

TODOs:
- [ ] Move ASRequiringMainThreadDeallocating related code out of `ASInternalHelpers`
- [ ] Decide if we would like to add the LRUCache at all 

Follow up PR to #598
Addresses #586

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextKitComponents.mm:</p>
<pre><code>//
//  ASTextKitComponents.mm
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) 2017-present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a2bd2146c200f0a8e59a7ecbe2beeeb7/raw/e95e7fb4dd471273d224c68c548b7cee65dc6fc4/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextKitComponents.mm:</p>
<pre><code>//
//  ASTextKitComponents.mm
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) 2017-present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/8be327fcf2886e6424145809237545d5/raw/6bf8c662c1d46c1875659984f1e506f195497093/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASRequiringMainThreadDeallocating.h:</p>
<pre><code>//
//  ASRequiringMainThreadDeallocating.h
//  Texture
//
//  Copyright (c) 2017-present, Pinterest, Inc.  All rights reserved.
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextKitComponents.mm:</p>
<pre><code>//
//  ASTextKitComponents.mm
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) 2017-present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/7675eec6ce7eb65a265560f4a2b3a853/raw/fb3d2ca164027c95bab510363e9c5a6023e232ba/log.txt)

**Comment by appleguy** [comment]
Thanks for exploring this and also #598!! This is an important line of investigation for a tricky issue...

Caching the results of conformsToProtocol: is really important, and I know you're very knowledgable about caches, so it's exciting to see the LRUCache idea :).

Should we just cache this kind of info (like "class X needs main thread deallocation: YES or NO") in an infinitely-sized cache instead of LRU? Can we use a C++ unordered_map, from void * (the singleton pointer of the class itself) to BOOL?

**Comment by maicki** [comment]
@appleguy We could just use and `unordered_map` for an infinitely-sized cache correct. It would work from `Class` to `BOOL`.

Closing in favor of #598

**Pull request closed without merging**
