### PR TITLE
Don't return non-animated GIFs for animation (update to latest PINRemoteImage beta)

### PR DESCRIPTION
**Pull request by garrettmoon**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/398e6936a2297dfe89343d6d40256f2b/raw/3a2de4dc1cb80cd87914c2328623608127fa2854/log.txt)

**Comment by garrettmoon** [comment]
Ah, need a new release of PINRemoteImage to make this happen…

**Comment by nguyenhuy** [comment]
@garrettmoon Any update on this?

**Comment by garrettmoon** [comment]
😅

**Pull request merged**
