### PR TITLE
Add support for collection view context menus

### PR DESCRIPTION
**Pull request by drinkius**

### CODE REVIEW

**Comment by drinkius** [comment]
It's a counterpart to #1795 which initially didn't support UICollectionView's updated API

**Comment by jparise** [comment]
@drinkius The CI check appears to be failing with a git error:

```
git checkout --progress --force ac6515566fd7316f3eee1c76e5a174609a452079
##[error]fatal: reference is not a tree: ac6515566fd7316f3eee1c76e5a174609a452079
```

Could you try rebasing your changes on top of the latest master commit and pushing again?

**Comment by bolsinga** [comment]
@drinkius Please try rebasing or merging again.

**Comment by bolsinga** [comment]
Is this covered by #1860 now?

**Comment by drinkius** [comment]
@bolsinga seems so, sorry, was swamped at work lately and didn't have time to add fixes

**Comment by bolsinga** [comment]
> @bolsinga seems so, sorry, was swamped at work lately and didn't have time to add fixes

No problem! I understand completely. Thanks!

**Pull request closed without merging**
