### PR TITLE
[Yoga] Increment Yoga version to current, 1.5.0.

### PR DESCRIPTION
**Pull request by appleguy**
Everything seems to build fine with this version, so I'll
seek clarifying information from the reporter of this bug:

https://github.com/TextureGroup/Texture/issues/25

### CODE REVIEW

**Comment by maicki** [comment]
@appleguy Do you use 1.3 already? Should we just merge it for now?

**Comment by appleguy** [comment]
We are currently on 1.5.0 -- check out the podspec in my latest WIP PR.

Feel free to merge this, does it actually help that other issue? Also fine
to use 1.5.0.

**Comment by maicki** [comment]
@appleguy Let's update this PR to 1.5 than and just merge it. Or what do you think?

**Comment by appleguy** [comment]
Sounds great!

**Comment by maicki** [comment]
@appleguy Ok cool will do that now.

**Comment by maicki** [comment]
@appleguy Can you give you final good to go with this PR in this case I will merge it. cc @weibel in case you would like to try out this PR.

**Comment by maicki** [comment]
@appleguy I will merge this now as it seems the upgrade will work fine.

**Comment by weibel** [comment]
This did not fix the issue I had. I have made this PR to show what was needed for me to make my particular project compile https://github.com/TextureGroup/Texture/pull/306

**Pull request merged**
