### PR TITLE
Passthrough pagingEnabled for ASCollectionNode / ASTableNode

### PR DESCRIPTION
**Pull request by maicki**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/d07f7d9fcdbc172862fd0b127e17b800/raw/eb9f2cadc29cebc522c8eca73f745c80a31e9f71/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/0343d45b2dd88a55d244e9a0fa7fa3d7/raw/b6ad4833b80f37627e6aff352e2a42caf4a1fad7/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/9260f5a2a2ad7dc37be68d659da95345/raw/0c79bacb21f0ce87928ea210837f0ea2adcca861/log.txt)

**Comment by nguyenhuy** [comment]
Test failure looks unrelated. Kicked off another test run.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/911a5e33df9c64a78e6c15c94f462991/raw/12dd017089941620e502ee956e993024c6efb7f0/log.txt)

**Comment by maicki** [comment]
@nguyenhuy @garrettmoon Could someone please take a look at the CI. All the previous failures are unrelated to the PR and seems like either flaky tests or stale Derived Data. Thanks!

**Comment by Adlai-Holler** [comment]
The error is buried, but I just hit it on my other PR yesterday. Basically isPagingEnabled is prohibited under tvOS so the pod spec won't lint, you've got to wrap that in `#if !TARGET_OS_TV`.

**Pull request merged**
