### PR TITLE
Fix ASTextNode2 is accessing backgroundColor off main while sizing / layout is happening

### LINKED ISSUE #767: ASTextNode2 crashes when used with transitionLayout shouldMeasureAsync:true
Crash output:

    0   CoreFoundation     0x000000010506212b __exceptionPreprocess + 171
    1   libobjc.A.dylib    0x00000001046f6f41 objc_exception_throw + 48
    2   CoreFoundation     0x00000001050672f2 +[NSException raise:format:arguments:] + 98
    3   Foundation         0x0000000104197d69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
    4   AsyncDisplayKit    0x0000000103bb99e2 -[ASDisplayNode(UIViewBridge) backgroundColor] + 418
    5   AsyncDisplayKit    0x0000000103d221df -[ASTextNode2 prepareAttributedStringForDrawing:] + 463
    6   AsyncDisplayKit    0x0000000103d213ec -[ASTextNode2 calculateSizeThatFits:] + 1052

So the flow for calculating size that fits for `ASTextNode2` is currently the following:
  - `calculateSizeThatFits` relies on `prepareAttributedStringForDrawing`
  - `prepareAttributedStringForDrawing` reads `backgroundColor` (it's not clear to me why this is required)
  - `backgroundColor` asserts `ASDisplayNodeAssertThreadAffinity`

This is an issue when using `transitionLayout(animated: true, shouldMeasureAsync: true)`.

I've played around with commenting out the color handling in `prepareAttributedStringForDrawing` and I've found that this fixes the issue.

### PR DESCRIPTION
**Pull request by maicki**
Fixes #767 

We can add the background only if we really prepare the attributed string only for drawing. We are calculating the layout without background color now and use it for sizing of the node that in the end will draw the attributed string with background color. Background color should not the influence the size though.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextNode2.mm:</p>
<pre><code>//
//  ASTextNode2.mm
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) through the present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/d01c20ff0a10c2d8e78a51dae0b480f2/raw/2617cec64b2809cf46c857ca605c43171578ebe4/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextNode2.mm:</p>
<pre><code>//
//  ASTextNode2.mm
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) through the present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by jinlee** [comment]
awesome! :+1:

**Pull request merged**
