### PR TITLE
Guard photo library with macro for tests

### PR DESCRIPTION
**Pull request by wsdwsd0829**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/1b516f3e2fc2abcf6c1495cedc04a339/raw/9a8a836d15586478754d2b4968c1427dd018437f/log.txt)

**Comment by nguyenhuy** [comment]
CI was flaky. The commit with actual code changes passed, so I'm gonna land this.

**Comment by nguyenhuy** [comment]
@wsdwsd0829 Thanks for the fix, btw.

**Comment by wsdwsd0829** [comment]
Ok, Thanks.

**Pull request merged**
