### PR TITLE
Fix compiler error in ASLocking #trivial

### PR DESCRIPTION
**Pull request by nguyenhuy**
Hitting this error because we're compiling with a stricter set of build rules internally.

nslockset

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a9c4a5c48a1ee5b1f96f8045f28697e9/raw/cead724cab7c540929a47070b462334fca5130e1/log.txt)

**Comment by nguyenhuy** [comment]
Good point, updated the diff. The compiler complaints about missing initialization for the lock set’s locks array (i.e locks.locks).

**Comment by nguyenhuy** [comment]
Looks like we do, but the engineer who's working on this project hasn't hit it yet (and I heard it's non-trivial for me to apply all of her changes). Will follow-up if need to.

**Comment by nguyenhuy** [comment]
Thanks btw!

**Pull request merged**
