### PR TITLE
[ASCollectionNode/ASTableNode] Fix a crash occurs while remeasuring cell nodes

### PR DESCRIPTION
**Pull request by nguyenhuy**
According to the stack trace below, this crash happened when `_cellsForLayoutUpdates` was mutated while being enumerated in `-[ASCollectionView layoutSubviews]`. Fix by making a copy of `_cellsForLayoutUpdates` (and immediately clear it) before passing it to `-[ASDataController relayoutNodes:nodesSizeChanged:`.

Apply the same fix to ASTableView.

screen shot 2018-05-11 at 4 40 21 pm

[Internal JIRA ticket](https://jira.pinadmin.com/browse/BUG-77357)

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nguyenhuy** [comment]
@Adlai-Holler Indeed, the only re-entrant path I can think of is `-setNeedsLayout` *and* `-layoutIfNeeded` being called during the re-measurement.

I agree that your solution sounds like the ideal behavior. However, since it'll be a bigger and riskier change, I'd propose to merge this diff as is and follow up on another diff. What do you think?

**Comment by Adlai-Holler** [comment]
Yep thats the way

**Comment by nguyenhuy** [comment]
Thanks!

**Pull request merged**
