### PR TITLE
Enable tvOS support

### PR DESCRIPTION
**Pull request by Eke**
Hello!

I re-enabled tvOS support which was disabled [by this commit](https://github.com/facebookarchive/AsyncDisplayKit/commit/2032cffd907d1740ebfc320f4e784b91d9938b66#diff-e275548079d7a46e0233837c70dfb71e).

At this moment everything works fine locally, but if there are some more details i need to know, please let me know. We have the project which needs tvOS support, so i'm ready to take this part over and fix everything.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/f82c72409723a86d50bfc7d4f1a28e4f/raw/74dafd203cdee0959759ba5ef800aeed008550c2/log.txt)

**Comment by Eke** [comment]
Thanks @nguyenhuy !

Strange, it was working locally.

I will take a look ASAP and will fix it.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/29eaa7bca6a786315a2fb20464d283f4/raw/9d4097d3356c3ecba6805f121dc9850065f1fc3e/log.txt)

**Comment by Adlai-Holler** [comment]
Superseded by #728 Thanks @Eke!

**Pull request closed without merging**
