### PR TITLE
Rework ASTraitCollection to Fix Warnings and Remove Boilerplate

### PR DESCRIPTION
**Pull request by Adlai-Holler**
This code was pretty messy.

This does include a small breaking change with an easy migration pathway. If users were calling `+[ASTraitCollection traitCollectionWithBlah:AndBlah:Etc:]` those are gone now. They were never supposed to be called. But there's an easy migration pathway using `+traitCollectionWithASPrimitiveTraitCollection:`.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/fa2298a28a39dae494641db2abb9265f/raw/e64ae4ba87c556e8791249e98d36e923418b2278/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/56eebec071ac5c59119808bde40aa034/raw/cc1977e1ad1cb4a629a2c3fb1817a011c345b445/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/d6789e3a73d5167b69882a77c0b0e0e3/raw/2b961dd0b794768a155e98e0f5bdcbd4c0f53aad/log.txt)

**Comment by Adlai-Holler** [comment]
The CI broke:
- `UIUserInterfaceStyle is not available on iOS.`
- But it is, in iOS 12, and it's marked correctly.
- Xcode 9 doesn't know that because it has the iOS 11 SDK.
- Two fixes:
  - Upgrade the CI to Xcode 10.
  - Make a new macro like `AS_INTERFACE_STYLE_AVAILABILITY` which expands to `#if __IPHONE_12 API_AVAILABLE(tvos(10), ios(12) #else API_AVAILABLE(tvos(10)) #endif`

The latter pattern doesn't scale. We should upgrade the CI to Xcode 10. Take a look at diff #1210!!

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/c3b1f97314f2472b29ca548819b676c1/raw/c1a427e9d52bcc1c7e6d031784c64a54e4c7cff1/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/5c76ab3afbc2a0ce8414e50d616009c3/raw/ed56532dda97fa9d8b5fea8aae1cabfe605b6fe8/log.txt)

**Pull request merged**
