### PR TITLE
[WIP] Finish rebranding from AsyncDisplayKit to Texture

### PR DESCRIPTION
**Pull request by Kaspik**
As a follow up on https://github.com/TextureGroup/Texture/issues/1045 I decided it's time to do this kinda complicated change.

More than year and half after @garrettmoon introduced on Medium that AsyncDisplayKit is now Texture [here](https://medium.com/@Pinterest_Engineering/introducing-texture-a-new-home-for-asyncdisplaykit-e7c003308f50), it's time to rename modules, app itself, project and CocoaPods pod.

This PRs tries to do that.
I wanted to do that after some stable release, but it's not coming so here it is.

Opening now for suggestions and ideas, will add more changes as all example projects needs to be updated as well.

**The king is dead, long live the king!**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/86d9cf7bb7fc1f0b9b48b97dfc69e8f3/raw/bc018b973aa92a2362b6dd4eaeea6b0d41b025d7/log.txt)

**Comment by nguyenhuy** [comment]
@Kaspik Thanks for submitting this diff. Do you have a plan to finish it?

**Comment by Kaspik** [comment]
Hey! There was no response for quite a long time so I paused that, but yeah, I can do it in next few days.

**Comment by nguyenhuy** [comment]
@Kaspik I've talked to the team about your change and we think we can include this in the coming 3.0 (time TBD). However, @Adlai-Holler and I think that this diff is too aggressive. For example, it changes `asyncdisplaykit_isAsyncTransactionContainer` to `texture_isAsyncTransactionContainer`, `asyncdisplaykit_node` to `texture_node`, etc.

We believe that we can get most of the benefits by updating `module_name`, `header_dir` and the umbrella header to Texture. That way developers only need to change their import statements and nothing else. What do you think?

**Comment by Kaspik** [comment]
Hmmm, it means revert this PR and do it again - which might be the best way anyways. Okay, I'll take care of that.

**Comment by Kaspik** [comment]
@nguyenhuy Opened another PR, let's move discussion there.

**Pull request closed without merging**
