### PR TITLE
Disable ASAssertLocked and ASAssertUnlocked by default

### LINKED ISSUE #1334: Thread should not hold lock
[Texture Version: p7.4]

Hi I hope this is the right forum for this but I am getting a Assertion after calling view.layoutIfNeeded() inside a UIView animation block. 

The function works correctly when the keyboard is displaying but in the case where the keyboard dismisses I am getting the failure. 

Code causing the assertion is self.view.layoutIfNeeded()
`
        UIView.animate(withDuration: animationDuration, delay: 0, options: animationCurve, animations: { [weak self] in

            guard let self = self else { return }
            
            self.additionalSafeAreaInsets.bottom = intersection.height
            self.view.layoutIfNeeded()
        }, completion: { [weak keyboardAwareVC] (completed) in

            keyboardAwareVC?.onKeyboardFrameDidChange()
        })
`

Log from assertion failure. 
`2019-02-06 07:14:43.665978-0800 Reach[9726:6494563] *** Assertion failure in void ASDN::Mutex::AssertNotHeld()(), /Users/john/Temp Projects/coClient/Pods/Texture/Source/Details/ASThread.h:204
2019-02-06 07:14:43.680439-0800 Reach[9726:6494563] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Thread should not hold lock'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011268a1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001092af735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112689f42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010cd94940 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   AsyncDisplayKit                     0x000000010ae7ab9d _ZN4ASDN5Mutex13AssertNotHeldEv + 589
	5   AsyncDisplayKit                     0x000000010aeb2092 -[ASDisplayNode __layout] + 514
	6   AsyncDisplayKit                     0x000000010adba17c -[_ASDisplayLayer layoutSublayers] + 492
	7   QuartzCore                          0x000000010f78b9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	8   UIKitCore                           0x000000011b86e077 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1429
	9   Reach                               0x0000000106acfa3b $SSo16UIViewControllerC5ReachE46_onKeyboardFrameWillChangeNotificationReceived33_2EBE1202122E2B2013B55245126FDE4ELLyy10Foundation0I0VFyycfU_ + 651
	10  Reach                               0x0000000106acfe95 $SSo16UIViewControllerC5ReachE46_onKeyboardFrameWillChangeNotificationReceived33_2EBE1202122E2B2013B55245126FDE4ELLyy10Foundation0I0VFyycfU_TA + 37
	11  Reach                               0x000000010663a45d $SIeg_IeyB_TR + 45
	12  UIKitCore                           0x000000011b876bf2 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 558
	13  UIKitCore                           0x000000011b8770cf +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 99
	14  Reach                               0x0000000106acf60b $SSo16UIViewControllerC5ReachE46_onKeyboardFrameWillChangeNotificationReceived33_2EBE1202122E2B2013B55245126FDE4ELLyy10Foundation0I0VF + 5179
	15  Reach                               0x0000000106acfbbc $SSo16UIViewControllerC5ReachE46_onKeyboardFrameWillChangeNotificationReceived33_2EBE1202122E2B2013B55245126FDE4ELLyy10Foundation0I0VFTo + 76
	16  CoreFoundation                      0x00000001125c9bac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	17  CoreFoundation                      0x00000001125c902f _CFXRegistrationPost + 447
	18  CoreFoundation                      0x00000001125c8d71 ___CFXNotificationPost_block_invoke + 225
	19  CoreFoundation                      0x00000001126afae2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	20  CoreFoundation                      0x00000001125c8694 _CFXNotificationPost + 964
	21  Foundation                          0x000000010cdf6589 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	22  UIKitCore                           0x000000011b183016 -[UIInputWindowController postStartNotifications:withInfo:] + 929
	23  UIKitCore                           0x000000011b185d88 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.1037 + 530
	24  UIKitCore                           0x000000011b876bf2 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 558
	25  UIKitCore                           0x000000011b877045 +[UIView(UIViewAnimationWithBlocks) _animateWithDuration:delay:options:animations:start:completion:] + 116
	26  UIKitCore                           0x000000011b1856bc -[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:] + 1695
	27  UIKitCore                           0x000000011b18dfce -[UIInputWindowController setInputViewSet:] + 1176
	28  UIKitCore                           0x000000011b184c79 -[UIInputWindowController performOperations:withAnimationStyle:] + 50
	29  UIKitCore                           0x000000011b20b489 -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 1637
	30  UIKitCore                           0x000000011b2033d6 -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] + 2352
	31  UIKitCore                           0x000000011b3c723b -[UIResponder _finishResignFirstResponder] + 267
	32  UIKitCore                           0x000000011b3c72fd -[UIResponder resignFirstResponder] + 140
	33  UIKitCore                           0x000000011b6f4dc4 -[UITextView resignFirstResponder] + 93
	34  UIKitCore                           0x000000011b869c05 -[UIView(Hierarchy) _removeFirstResponderFromSubtree] + 167
	35  UIKitCore                           0x000000011b86a1b5 __UIViewWillBeRemovedFromSuperview + 72
	36  UIKitCore                           0x000000011b869fbc -[UIView(Hierarchy) removeFromSuperview] + 95
	37  AsyncDisplayKit                     0x000000010aec57c1 -[ASDisplayNode _removeFromSupernode:view:layer:] + 177
	38  AsyncDisplayKit                     0x000000010aec5627 -[ASDisplayNode _removeFromSupernodeIfEqualTo:] + 951
	39  AsyncDisplayKit                     0x000000010af2166d -[ASLayoutTransition applySubnodeInsertionsAndMoves] + 845
	40  AsyncDisplayKit                     0x000000010af21318 -[ASLayoutTransition commitTransition] + 72
	41  AsyncDisplayKit                     0x000000010ae83357 -[ASDisplayNode(ASLayoutTransition) _completeLayoutTransition:] + 215
	42  AsyncDisplayKit                     0x000000010ae8321f -[ASDisplayNode(ASLayoutTransition) _completePendingLayoutTransition] + 223
	43  AsyncDisplayKit                     0x000000010ae7c8ec -[ASDisplayNode(ASLayoutInternal) _u_measureNodeWithBoundsIfNecessary:] + 4524
	44  AsyncDisplayKit                     0x000000010aeb240c -[ASDisplayNode __layout] + 1404
	45  AsyncDisplayKit                     0x000000010adba17c -[_ASDisplayLayer layoutSublayers] + 492
	46  QuartzCore                          0x000000010f78b9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	47  QuartzCore                          0x000000010f7047ca _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 342
	48  QuartzCore                          0x000000010f73b97e _ZN2CA11Transaction6commitEv + 576
	49  QuartzCore                          0x000000010f73c6fa _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	50  CoreFoundation                      0x00000001125eec27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	51  CoreFoundation                      0x00000001125e90be __CFRunLoopDoObservers + 430
	52  CoreFoundation                      0x00000001125e9751 __CFRunLoopRun + 1537
	53  CoreFoundation                      0x00000001125e8e11 CFRunLoopRunSpecific + 625
	54  GraphicsServices                    0x0000000115a321dd GSEventRunModal + 62
	55  UIKitCore                           0x000000011b39981d UIApplicationMain + 140
	56  Reach                               0x00000001071ba217 main + 71
	57  libdyld.dylib                       0x000000011449f575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

### PR DESCRIPTION
**Pull request by nguyenhuy**
After talking to @maicki about the current locking situation and the idea of potentially having a transaction lock separated from node's instance lock in the future, I think it's best to disable these assertions for now.

I didn't remove the assertions entirely because I think for now they still provide valuable information regarding the locking expectation/requirement of the method that has them. We'll remove them when such information is no longer useful and/or valid.

Closes #1334, #1404.

### CODE REVIEW

**Comment by wiseoldduck** [comment]
I really like the idea of a transaction lock distinct from a more granular instance lock.

I don't like the way this disable is being done though, it leads to very misleading code that still seems to be asserting things. I would prefer to see the asserts removed or commented-out at the call sites.

**Comment by grangej** [comment]
Any progress on this? This is a huge issue and still blocking updating to 2.8.

**Comment by nguyenhuy** [comment]
@wiseoldduck I don't like it neither. Having what seems to be assertions at call sites that do nothing isn’t ideal, but in some reports, the number of call sites are numerous due to what some client code is trying to do. I consider this a temporary fix that buys us some time to address the internal locking mechanism.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Adlai-Holler** [comment]
I agree with Kevin, I think a better diff is to rename the macro to `DISABLED_ASAssertLocked` or similar so that readers know it doesn't do anything.

**Comment by Adlai-Holler** [comment]
Follow up to last comment, obviously that'll mean no build flag but I think that's OK. We won't use it.

**Comment by nguyenhuy** [comment]
Added a DISABLE prefix. It allows us to communicate the fact that the assertions do nothing and the original locking intention/requirement/dream.

**Comment by wiseoldduck** [comment]
+1 LGTM

**Comment by wiseoldduck** [comment]
I don't really have any formal approval powers 🤷‍♀️ but I am morally behind merging this

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/ed18d01246f72cd0f6dcc6e899640043/raw/3103d4f654ec741f1ab91b2aba9ce5b9763f9bb8/log.txt)

**Comment by nguyenhuy** [comment]
Cool. Thanks everyone!

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/bedbf24a6b545c50e38818420d6742ac/raw/8975778f941d671b8062389d9d343b15457e88bf/log.txt)

**Pull request merged**
