### PR TITLE
[ASDKGram Example] image_url has been changed from URL string to Array by 5…

### PR DESCRIPTION
**Pull request by kaar3k**
https://api.500px.com/v1/photos?feature=popular&exclude=Nude,People,Fashion&sort=rating&image_size=3&include_store=store_download&include_states=voted&consumer_key=Fi13GVb8g53sGvHICzlram7QkKOlSDmAmp9s9aqC&page=1&rpp=4&image_size=600

CHECK **image_url**

### CODE REVIEW

**Comment by nguyenhuy** [comment]
@kaar3k While you're at it, please fix the warning posted by the bot above. Thanks!

**Comment by kaar3k** [comment]
@nguyenhuy Thank you :) . Updated the Pull Request as requested.

**Comment by appleguy** [comment]
@kaar3k I'd just noticed this crash yesterday and wasn't sure if it was something else locally - thank you for posting the PR quickly!

**Comment by kaar3k** [comment]
@maicki  Thanks for reviewing.. :)

**Comment by kaar3k** [comment]
@appleguy  Thanks for Accepting the PR :)

**Comment by jsonpoindexter** [comment]
The URL in the example now returns:

> {"error":"Application is deactivated, please contact us by email: help@500px.com.","status":403}

**Comment by garrettmoon** [comment]
@jsonpoindexter sadly 500px shut down their API. In master we use unsplash now: https://github.com/TextureGroup/Texture/pull/938

**Comment by jsonpoindexter** [comment]
@garrettmoon thanks for the reply! I see it was changed to unspash for ObjC, while I was trying the swift example. Thanks again!

**Pull request merged**
