### PR TITLE
Adds support for using UIGraphicsImageRenderer in ASTextNode.

### PR DESCRIPTION
**Pull request by garrettmoon**
In many cases this reduces the backing store of text nodes by 1/2.

### CODE REVIEW

**Comment by garrettmoon** [comment]
I think the biggest change that *won't* be captured by an experiment is the switch from `drawRect:` to `displayWithParameters:`. Anyone have any concerns with that?

**Comment by garrettmoon** [comment]
If this goes well I'll likely attempt this in ASImageNode as well.

**Comment by maicki** [comment]
We still support iOS 9 within our Podspec and UIGraphicsImageRenderer is iOS10+  so I think we need to guard against it for the time.

**Comment by garrettmoon** [comment]
@Adlai-Holler Yes, if all experiments are successful 🤞 then I'll keep moving this up the stack.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/4c794e647c96f85ccaaa582730479ad2/raw/d06bf440ed08f93913b569515198846a463c02dc/log.txt)

**Pull request merged**
