### PR TITLE
Fix CustomCollectionView-Swift sample

### PR DESCRIPTION
**Pull request by george-gw**
The sample was crashing, the crash was reported on Slack.
This is a quick fix

### CODE REVIEW

**Comment by maicki** [comment]
@Adlai-Holler Did this change due to our initializer changes?

**Comment by Adlai-Holler** [comment]
@george-gw @maicki Could someone link to the Slack conversation about the issue, and open a GitHub issue for it? I searched around but couldn't find it.

**Comment by george-gw** [comment]
@Adlai-Holler https://github.com/TextureGroup/Texture/issues/39

**Comment by pinterest-ios** [comment]
Build failure:

**Comment by maicki** [comment]
@Adlai-Holler Any thoughts on it based on the issue? Did the initializer changed due to our changes?

**Comment by maicki** [comment]
Hey @george-gw can you please rebase your PR. Thanks!

**Pull request merged**
