### PR TITLE
[ASVideoNode] fix bug ASVideoNode

### PR DESCRIPTION
**Pull request by FengDeng**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nguyenhuy** [comment]
@flovouin Sorry to ping you again, but does this look like the correct fix?

**Comment by flovouin** [comment]
Hi @nguyenhuy
It looks OK to me, but a sample project would be nice. I can take care of it, but it won't be before two weeks. Or maybe @FengDeng could share a piece of code demonstrating the problem and how this diff solves it?
Cheers,

**Comment by FengDeng** [comment]
@flovouin 
Perhaps it's Apple's bug? When i use ASVideoNode,AVPlayerItem's rate awalys return before AVPlayer's state.Then in ASVideoPlayNode can't receive ReadyToPlay.

`if (toState == ASVideoNodePlayerStateReadyToPlay) {
    _duration = _videoNode.currentItem.duration;
    [self updateDurationTimeLabel];
  }`

up code jump ASVideoPlayNode can't update durationTimeLabel.

**Comment by nguyenhuy** [comment]
@FengDeng I'm gonna close this PR for now. Please retest with latest master and open another PR if the issue is still there. Thanks all!

**Pull request closed without merging**
