### PR TITLE
These are also designated initializers

### PR DESCRIPTION
**Pull request by garrettmoon**

### CODE REVIEW

**Comment by plarson** [comment]
Should these be in there as well?

- (instancetype)initWithLayerBlock:(ASDisplayNodeLayerBlock)layerBlock;
- (instancetype)initWithLayerBlock:(ASDisplayNodeLayerBlock)layerBlock didLoadBlock:(nullable ASDisplayNodeDidLoadBlock)didLoadBlock;

**Comment by garrettmoon** [comment]
@plarson I think so, lemme update.

**Comment by pinterest-ios** [comment]
Build failure:

**Comment by garrettmoon** [comment]
I'm actually going to close this for now, I think it was intentional.

**Pull request closed without merging**
