### PR TITLE
Assert node did load before did enter visible way 1

### PR DESCRIPTION
**Pull request by wsdwsd0829**
Let's discuss which way is better #887

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by maicki** [comment]
@wsdwsd0829 Can you add an entry to the changelog please.

**Comment by appleguy** [comment]
@wsdwsd0829 is this still the latest patch, or did we merge a different solution already? Let's update this and ask for a review once it's ready, if still applicable.

**Comment by wsdwsd0829** [comment]
This is the latest, let's try to merge this.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/d4ad22d28c128f830eb9ab598bd596da/raw/b4832b63f356231c411c1aba268f43c81512c421/log.txt)

**Pull request merged**
