### PR TITLE
[CGPointNull] Rename globally exported C function to avoid collisions #trivial

### PR DESCRIPTION
**Pull request by appleguy**
Some other frameworks also declare this. Let's try to minimize collisions
without making the name too ugly.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
Build failure:
https://gist.githubusercontent.com/pinterest-ios/b7f8f80844398452f6fb112f52aed136/raw/77939b8e005f8879f6622757046816e045192128/results.txt

**Comment by maicki** [comment]
@appleguy Happy to approve and land after fixing the build error ... seems like you missed a place were we used `CGPointNull`.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by maicki** [comment]
@appleguy I would like to get that in sooner or later so I fixed the remaining problem.

**Comment by appleguy** [comment]
@maicki thank you! I just wrapped up a key work milestone today and was circling back to fix this. It's a great surprise to have it already pushed :).

This is still blocked on a review, so once it is accepted we can land it. Feel free to trigger the merge once you're ready.

**Pull request merged**
