### PR TITLE
Fix ASBasicImageDownloader Fatal Exception: Key (*URL) cannot be nil

### PR DESCRIPTION
**Pull request by GeekTree0101**

### CODE REVIEW

**Comment by hashemp206** [comment]
the top crash reason in my app is because of this!
is this pull request a solution? and if so when it will be merged?

**Comment by hashemp206** [comment]
@Adlai-Holler in my NetworkImageNode, I check against null url, but still I have encounter this crash!
I think the url is getting nil under the hood! still confused, if it is Texture bug? or should I do some precautions?

**Comment by GeekTree0101** [comment]
In Texture 2.7, ASBasicImageDownloaderContext crash increased 6 times rather then Texture2.6
```Fatal Exception: NSInvalidArgumentException
*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil, ASThread.h line 416
+[ASBasicImageDownloaderContext contextForURL:]```

**Comment by GeekTree0101** [comment]
https://github.com/TextureGroup/Texture/pull/1019 i just reopen this issue

**Pull request closed without merging**
