### PR TITLE
[Issue 838] Update ASCeilPixelValue and ASRoundPixelValue

### PR DESCRIPTION
**Pull request by rcancro**
Layouts can come back for 3x devices as a repeating decimal. Floats/doubles have a hard time representing these values and often the last digit or two will be  garbage. This garbage can result in unexpected values from `ceil` or `round`. I try to fix this by subtracting `FLT_EPSILON` from the value before calling `ceil` or `round`

https://github.com/TextureGroup/Texture/issues/838

### CODE REVIEW

**Comment by wiseoldduck** [comment]
Yes I think `ASFloorPixelValue` would want `+FLT_EPSILON`, and `ASRoundPixelValue` would want to be left alone.

**Comment by Adlai-Holler** [comment]
I am not a smart man… is it worth using ASCeilPixelValue? It seems like it's asking for this kind of trouble, and subpixel clipping of content isn't a serious risk.

Anyway, I support landing this change. I can't think of how it could produce bad results in practice.

**Comment by wiseoldduck** [comment]
Yes fair warning I am quite naive as to how this is used in practice!

But am pretty sure if you apply this to `ASRoundPixelValue` and can come up with examples where it mattered it would be incorrect about half the time.

**Comment by wiseoldduck** [comment]
OK I see the example in the comments cites `100.666666666669`, not what I was expecting to see  like `100.666666666667`, where we were addressing just the inability to capture a nonterminating rational in a `CGFloat`. There is apparently some other source of inaccuracy than that! I will take this conversation somewhere else as it is now more about my enlightenment than constructive review.  😄

**Comment by rcancro** [comment]
@wiseoldduck I think you are right -- We probably shouldn't do anything to round. I'll remove that.

@Adlai-Holler When creating an ASLayout, it uses `ASCeilPixelValue` on the given size. I don't know the performance implications, but in the past making sure you staying on pixel bounds was important for keeping text and images crisp.

**Pull request merged**
