### PR TITLE
[ASImageNode] Add documentation for image effects #trivial

### PR DESCRIPTION
**Pull request by maicki**

### CODE REVIEW

**Comment by nguyenhuy** [comment]
Nice write up! Since we already have a dedicated [page for image modification blocks](http://texturegroup.org/docs/image-modification-block.html), maybe we should have a new image effects section with a short explanation, but then link to that page.

**Comment by maicki** [comment]
@nguyenhuy Agree. I will take another step on that soon when time allows.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by maicki** [comment]
@nguyenhuy Added changes based on your feedback.

**Comment by nguyenhuy** [comment]
@maicki Hm, the new code snippets aren't rendered correctly: http://texturegroup.org/docs/image-modification-block.html. Could you please take a look?

**Comment by maicki** [comment]
@nguyenhuy Yep will take a look

**Pull request merged**
