### PR TITLE
Remove misleading comment and add assertion #trivial

### PR DESCRIPTION
**Pull request by wiseoldduck**
The comment at line 305 strongly implies this is expected to be a dynamic cast.

### CODE REVIEW

**Comment by nguyenhuy** [comment]
On a second thought, I think @Adlai-Holler is right. These find nodes functions are called with flattened layouts only.

**Comment by wiseoldduck** [comment]
Nooooooooooo!

Yeah no, actually I agree - I forgot I had made this PR. It all makes sense I will adjust.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/73edad0963812507503e2102dcbfdf8f/raw/4af22add0508a1cbd9236167bc0bd5f31ab9b8e9/log.txt)

**Comment by wiseoldduck** [comment]
@maicki Done-and-done

**Pull request merged**
