### PR TITLE
[ASTextNode] insets considered touches refs #255 #298

### PR DESCRIPTION
**Pull request by SergeyPetrachkov**

### CODE REVIEW

**Comment by Petrachkov** [comment]
Hi there! I've implemented a fix for the case I described above. See kindly attached links to source codes and videos where i tried to show the problem. 

ASTextNodeFixed.zip
ASTextNodeOriginal.zip

https://drive.google.com/open?id=0B700EvOP9QOFcEg2WUxNaHNRQjA
https://drive.google.com/open?id=0B700EvOP9QOFMU9UbGFJdzBMZHc

**Comment by Petrachkov** [comment]
See kindly attached some related links :
http://stackoverflow.com/questions/43995120/open-tapped-links-in-uitextview-without-html
http://stackoverflow.com/questions/19332283/detecting-taps-on-attributed-text-in-a-uitextview-in-ios

**Comment by Petrachkov** [comment]
Please also try changing the code from provided sample called ASTextNodeOriginal for **textNode1** to:

```
lazy var textNode1 : ASTextNode = {
        var node = ASTextNode();
        node.highlightStyle = .light;
        node.layer.as_allowsHighlightDrawing = true;
        let parStyle = NSMutableParagraphStyle();
        parStyle.alignment = NSTextAlignment.left;
        parStyle.lineBreakMode = NSLineBreakMode.byWordWrapping;
        parStyle.lineSpacing = 5;
        
        let attrStr = NSMutableAttributedString(string: self.text1,
                                                attributes: [
                                                    NSFontAttributeName: UIFont.systemFont(ofSize: 14),
                                                    NSParagraphStyleAttributeName: parStyle,
                                                    NSForegroundColorAttributeName : UIColor(red: 79.0/255, green: 79.0/255, blue: 79.0/255, alpha: 1)
            ]);
        var linkAttributes : [String : Any] = [
            NSFontAttributeName: UIFont.systemFont(ofSize: 14),
            NSForegroundColorAttributeName: UIColor(red: 67.0/255, green: 154.0/255, blue: 208.0/255, alpha: 1),
            ];
        
        linkAttributes["TextLinkAttributeName"] = NSURL(string: "sergey.petrachkov.actonica");
        attrStr.addAttributes(linkAttributes , range: NSRange(location: 97, length: 26));
        node.linkAttributeNames = [ "TextLinkAttributeName" ];
        node.isUserInteractionEnabled = true;
        node.style.layoutPosition = CGPoint.zero;
        node.textContainerInset = UIEdgeInsets(top: 30, left: 30, bottom: 9, right: 12);
        node.attributedText = attrStr;
        return node;
    }()
```

the problem will be more obvious. Moreover, there is a problem with highlighter, you'll see it too. Highlighted area will be too big. I'll try to look into it when I have time.

**Comment by Petrachkov** [comment]
Moreover, if i comment these lines:

```
          rendererRect.size.width += _textContainerInset.left + _textContainerInset.right;
          rendererRect.size.height += _textContainerInset.top + _textContainerInset.bottom;
```

at 740 and 740 position of ASTextNode.mm inside 

`- (void)_setHighlightRange`

then i get the right highlight area

**Comment by Petrachkov** [comment]
[ASTextNodeFixed_withFixedHighilighter.zip](https://github.com/TextureGroup/Texture/files/1015880/ASTextNodeFixed_withFixedHighilighter.zip)

see kindly updated sample project with the latest fixes;

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/16c22396995a4ef852014e300ef3acb1/raw/e5195096df3e865b4dc5bf846e5f7242c4da4a31/log.txt)

**Comment by SergeyPetrachkov** [comment]
hey guys, how do i initiate rebuild? i guess the issue that caused CI/Pinterest failure has been fixed, so it should not be a problem to get all stages green.

**Comment by maicki** [comment]
@SergeyPetrachkov Can you rebase on top of master and push again. This should initiate a re-build

**Comment by SergeyPetrachkov** [comment]
@maicki done!

**Comment by maicki** [comment]
@SergeyPetrachkov Hey, unfortunately this looks like not the way it should be.

The necessary steps on your side would be:

1. Sync your fork's master with upstream (Texture's) master branch. You can find some more details in here: https://help.github.com/articles/syncing-a-fork/
2. Rebase your ASTextNode_InsetsConsideredTouches branch on top of your fork's master branch
3. Force push to your ASTextNode_InsetsConsideredTouches branch

Let me know if you have some further questions - we will get that figured out!

**Comment by garrettmoon** [comment]
I'm trying to figure out why this didn't build again…

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a2691a566e53f838e091f2b975a1aefd/raw/ae13c05bba1cacf52927f3f1edf8ce3f3d69343e/log.txt)

**Comment by garrettmoon** [comment]
@SergeyPetrachkov I believe the latest reported failure is valid. You can run the tests locally by invoking `./build.sh all`

**Comment by SergeyPetrachkov** [comment]
@garrettmoon  hmm, yes, i can see that :

❌  error: umbrella header for module 'AsyncDisplayKit' does not include header '/Users/sergeypetrachkov/TextureFork/Source/AsyncDisplayKit+IGListKitMethods.h' [-Werror,-Wincomplete-umbrella]



❌  error: umbrella header for module 'AsyncDisplayKit' does not include header '/Users/sergeypetrachkov/TextureFork/Source/IGListAdapter+AsyncDisplayKit.h' [-Werror,-Wincomplete-umbrella]



❌  /Users/sergeypetrachkov/TextureFork/Tests/ASBasicImageDownloaderContextTests.m:18:9: could not build module 'AsyncDisplayKit'

after running the script. Even though this should be fixed. Ok, ill take a look at what i did wrong while rebasing.

**Comment by maicki** [comment]
@SergeyPetrachkov Hey - I just rebased your branch on top of master and you can see the result here: https://github.com/TextureGroup/Texture/tree/SergeyPetrachkov-ASTextNode_InsetsConsideredTouches

As already described above these are the necessary steps from your side to get your branch rebased on top of master:
1. Sync your fork's master with upstream (Texture's) master branch. You can find some more details in here: https://help.github.com/articles/syncing-a-fork/
2. Rebase your ASTextNode_InsetsConsideredTouches branch on top of your fork's master branch:
    - `git checkout ASTextNode_InsetsConsideredTouches`
    - `git rebase master`
3. Resolve all merge conflicts while rebasing
4. After the rebase was successful, force push to your ASTextNode_InsetsConsideredTouches branch: `git push -f`

That said after rebasing you will see that after that 2 snapshot tests will fail: `testTextContainerInsetIsIncludedWithSmallerConstrainedSize` and `testTextContainerInsetHighlight`. After you run the test within Xcode via `CMD+u` you will see how you can search for a text like `If you have Kaleidoscope installed you can run this command to see an image diff:` and after that is a command you can execute in  the terminal to see the difference between the original snapshot and the snapshot after you change and you can go from there try to fix that.

Thanks!

**Comment by SergeyPetrachkov** [comment]
@maicki  Hi Michael! I've managed to sync repo and rebase. And now i see failed tests. I understand that those tests were made to compare images of highlighted texts (desired image and an image resulted by our code). Ok, it's failing, no problem. But have you taken a look at examples i attached above (video & source code)? My seems-to-be-fix resolves the issue i faced so i though you might want to take a look at the problem some might face while working with the framework. Im not claiming that my fix is 100% right, but i just wanted to address the problem that exists. 
Regards, 
Sergey

**Comment by garrettmoon** [comment]
@SergeyPetrachkov I'm not sure what you'd like us to do at this point? We can't merge code that breaks tests; if the tests are wrong, we should update them. If you're not willing to fix the code to fix the tests then you should open an issue instead of a PR?

Hope this helps!

**Comment by SergeyPetrachkov** [comment]
@garrettmoon i'll take a look at it when i have time. Unfortunately now i'm too busy on my projects to spend time fixing the issue. I assume it's not something critical or wide-known issue and people can live with it for now.

With kind regards,
Sergey

**Comment by garrettmoon** [comment]
@SergeyPetrachkov no problem, thank you for continuing to investigate! For now I'm going to close this PR (just to keep things clean). Please reply back here (and I'll re-open) or put up a new PR.

**Pull request closed without merging**
