### PR TITLE
[#1451] Add support for UIAccessibilityCustomAction

### PR DESCRIPTION
**Pull request by shamanskyh**
This PR adds support for UIAccessibilityCustomAction propagation through ASPendingState so that it can be picked up by VoiceOver.

### CODE REVIEW

**Comment by shamanskyh** [comment]
Hey @maicki any chance you could take a look at this? We'd like the `accessibilityCustomActions` property of nodes to propagate through.

**Comment by maicki** [comment]
@wsdwsd0829 Could you also take a look over this. Thanks!

**Comment by shamanskyh** [comment]
Hey @wsdwsd0829 and @maicki (and @bolsinga!), thanks so much for taking a look at this.

We're pushing to get some accessibility improvements in by a deadline and I'd like to get this in soon so we don't have to make Pinterest point at my fork. Any chance you could take a second look some time soon?

**Comment by shamanskyh** [comment]
(didn't mean to close, sorry)

**Pull request merged**
