### PR TITLE
Avoid dealloc on background

### PR DESCRIPTION
**Pull request by wsdwsd0829**
The node can be deallocated on background and causing crash when it try to access view/gesture recognizers in dealloc. 
ASMainThreadDeallocation.h should handle the ivar deallocation, thus we do not need to do it ourselves here

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/4bdb75d289bcd371e46828457b84b916/raw/389d863cb7c0e0a4e67ab2ee17c2b3c341121ffb/log.txt)

**Comment by Adlai-Holler** [comment]
@wsdwsd0829 could you rebase to kick the ci?

**Comment by wsdwsd0829** [comment]
is rebase reword enough to trigger test?

**Comment by nguyenhuy** [comment]
Yes, should finish in about 2 hours. Yes, that’s our new build time after upgrading Xcode :(

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/5f45cbe935996f2704efb5526bbb7fe8/raw/389d863cb7c0e0a4e67ab2ee17c2b3c341121ffb/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/6e6d2d14eb80dd8bf988f8765a94240c/raw/071b4ac788b56b923fc352baa6b47340ce4ea7d2/log.txt)

**Comment by nguyenhuy** [comment]
Agh, seems like a persistent CI issue.

**Comment by garrettmoon** [comment]
Can you rebase on master, this doesn't have the updated ./build.sh

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/5ad19ecf9051118d8202c0380e4ea7eb/raw/071b4ac788b56b923fc352baa6b47340ce4ea7d2/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/05b7e308deec8cf34325461e49e08369/raw/389d863cb7c0e0a4e67ab2ee17c2b3c341121ffb/log.txt)

**Comment by wsdwsd0829** [comment]
somehow messed up here, create a new one: https://github.com/TextureGroup/Texture/pull/1410

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/90342625f4d7581cbdad2ce210c7a5c3/raw/389d863cb7c0e0a4e67ab2ee17c2b3c341121ffb/log.txt)

**Pull request closed without merging**
