### PR TITLE
[ASDataController] Apply new visible map inside batch updates block

### PR DESCRIPTION
**Pull request by nguyenhuy**
Fixes https://github.com/TextureGroup/Texture/issues/378. Tested with the project attached in that report and smoke tested ASDKgram.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/59e3e1e68e0fd76ac491f2b0baa60657/raw/475109744cc89db30446ce3d9b1e5440680f2ab3/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/41645bebaf051418736a4d36a70e2466/raw/9b21bb8c6811bf520e8814f86b28abaa894fa893/log.txt)

**Comment by nguyenhuy** [comment]
Alright, merging. Thanks guys!

**Pull request merged**
