### PR TITLE
Remove ASEventLog

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Bye-bye! We now have better log support from the OS, so that will be the direction for the future.

We will add a flag to ASDisplayNode to enable logging on a per-node (or maybe per-tree) basis. In effect, each log statement will do `os_log(_log ? ASLayoutLog() : OS_LOG_DISABLED, "my log", ...)`.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/2851396d7e6c4baed6b4f3e52ede58ae/raw/7f9d62902d4bbe9ae0d782db3a94f6b7cda9bc2c/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/bfa55ac9d4a6d126d9f8e33c47827cc4/raw/eaed66dba63d3eef6ca446b4f33ba5328518fe20/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/fb10465e88a05f358bbbbf7c4c4c2a0e/raw/82d45adf4380a5c87d43fe99703c270a2c184f2e/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a87bfb5bcba81ead96fafa8f9aa60484/raw/e6f71c31622e29ea55813ee8d5eb6bcd296c8064/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/80bc42575600d1bec68127723a726a94/raw/0bfff1e07b6cdb27dd74ccf19d98c264f58807fe/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/7d67ab9f91bc3b07de3e5b48227d1f13/raw/258e0ecd1ca793b08f817e696317c1b8bd4f8b87/log.txt)

**Comment by Adlai-Holler** [comment]
@maicki @nguyenhuy Could you review this when there's time?

**Comment by Adlai-Holler** [comment]
FWIW I removed the `_addSubnode:` and friends because the non-underbar versions just had ASEventLog code in them.

**Pull request merged**
