### PR TITLE
add ASTextNode2 snapshot test

### PR DESCRIPTION
**Pull request by wsdwsd0829**
Just copy over from ASTextNode and enable experiment. 
  // All tests are duplicated from ASTextNodeSnapshotTests.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/b88c0f4feaba8a7a25c1ab4c534a2d7f/raw/921473aff37dcded52f8dd8456dde9ae75a5a442/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/ca208caa0b5c582ace94510ac6ccf3e9/raw/aa5e022654493e243baefded55f65f1697091061/log.txt)

**Comment by wsdwsd0829** [comment]
Ok, I am a little confused, the tests seems so comparing images from TextNode1. 
From what I recorded it locally, it supposed to create a new folder with name of this new test class. 

Will try enable record mode and rely on CI to create snapshots itself and then disable it, hopefully it can fix CI fails.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/6bdb4560eb47178e983f812037e1aae2/raw/7420424c97334947b2f13fbf39259140d0025be3/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/b97543ab2a5600d410c32df2153217f3/raw/a3de0f183ac78bd0dd1874da04d1b1703b32161b/log.txt)

**Comment by wsdwsd0829** [comment]
May needs some suggestions on this. It's seems comparing with TextNode1's images.

**Comment by Adlai-Holler** [comment]
It appears that FBSnapshotTestCase will use whatever reference image it matching the test selector that it finds first.

The easiest fix is to rename the methods to e.g. `testTextContainerInset2` and put a comment at the top explaining why we did and linking to this PR.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/6cb30805d6e12f17900a223e57e4ff10/raw/2a6360abcfdc7331c527314791351b20bd36e8cf/log.txt)

**Comment by Adlai-Holler** [comment]
@wsdwsd0829 It looks like the issue is that the ASTextNode1 tests are running after the ASTextNode2 tests, and there's currently no way to go *back* to ASTextNode1 once you enable ASTextNode2. 

So the TextNode1 tests are running with TextNode2 enabled.

**Comment by Adlai-Holler** [comment]
@wsdwsd0829 We're working on getting the CI back up and running.

**Comment by pinterest-ios** [comment]
## Danger has errored
[!] Invalid `safeToBuildAutomatically` file: SIGHUP. Updating the Danger gem might fix the issue. Your Danger version: 5.5.10, latest Danger version: 5.6.2

```
 #  from /Users/buildkite/CI/safeToBuildAutomatically:212
 #  -------------------------------------------
 #  %x(echo "#{pipeline}" > pipeline)
 >  %x(echo "#{pipeline}" | buildkite-agent pipeline upload)
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by wsdwsd0829** [comment]
Thanks for suggestions and fixing this.

**Comment by Adlai-Holler** [comment]
Very great diff! This will let us iterate on ASTextNode2 safely ❤️

**Pull request merged**
