### PR TITLE
[GitHub CI] Bad actor

### PR DESCRIPTION
**Pull request by huynguyendev**
So, can I modify the workflow file and get it executed without permissions?

### CODE REVIEW

**Comment by huynguyendev** [comment]
Hm, this is quite unexpected. Reported to GitHub [here](https://github.community/t5/GitHub-API-Development-and/GitHub-Action-workflow-is-executed-for-a-PR-from-a-forked-repo/m-p/29579#M2655).

**Comment by bonepartek1443** [comment]
Belk

**Comment by Matthew1234567w** [comment]
#1628

**Comment by Matthew1234567w** [comment]
Please bro

**Pull request closed without merging**
