### PR TITLE
Run Import Optimizer on Texture

### PR DESCRIPTION
**Pull request by bolsinga**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/38f754246055ef92c3af102704ff3ccd/raw/282b503d530733cd839b784489269c341d30021c/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/5fcda7945a694b5bc16059b08a4065e5/raw/5e39b1a88c91a96c96de6a701aaf1caa13c4d7f2/log.txt)

**Comment by bolsinga** [comment]
> That looks great! Curious what Import Optimizer did you run?

AppCode

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/0d0dd1b3177b58e004c123726ced546f/raw/286d78cb394d402d7b2356fef618dce46ebdabf7/log.txt)

**Pull request merged**
