### PR TITLE
[Project clean up] Reorganize project dir #trivial

### PR DESCRIPTION
**Pull request by nguyenhuy**
I found this neat tool called [Synx](https://github.com/venmo/synx) that updates the project dir to match XCode groups declared in `AsyncDisplayKit.xcodeproj`.  This is quite important because CocoaPods determines public headers by looking at the project directory.

Here are the changes:
- Rename `ASCollectionInternal` to `ASCollectionViewInternal`.
- Move `ASCollectionViewInternal`, `ASWeakProxy`, `ASTraceEvent` and `_ASTransitionContext` to `Source/Private`, and thus don't expose them via CocoaPods.
- Move `ASDisplayNode+Ancestry`, `ASPINRemoteImageDownloader` and `ASSectionContext` to `Source`.
- Move `ASRunLoopQueue` to `Source/Details`.
- Move files related to async collection layout to `Source/Details/Collection Layout`.
- Move files related to `ASDataController` to `Source/Details/Data Controller`.
- Move `ASSection` and `ASDelegateProxy` to `Source/Private/Data Controller`.
- Move `AsyncDisplayKit.modulemap` and `Info.plist` to `Source/Supporting Files`.
- Move tests-related files to the correct dirs.
- Sort XCode entries and groups by name.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/f343142cc66ffefb2c309be9ce48f489/raw/82f96632db58f065dbe058ca3022891ba961f31b/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by appleguy** [comment]
In my project, we're required to use direct paths for everything, so this does add some inconvenience - but I'm fully supportive especially if we can make a small number of larger changes rather than tweaking it frequently.

About the files moving private - ASWeakProxy seems simple and useful enough to leave available? Not a big deal (although I am using it, these rules won't apply due to no cocoapods).

The /Details folder will remain publicly exported, right?

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/f252d4ddad15503e440148d5eee67fec/raw/c0fcf25e31b048b80b922231ea1ae32f05ff2ea7/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big PR, please consider splitting it up to ease code review.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by appleguy** [comment]
Looking good, thanks for doing this!

**Comment by nguyenhuy** [comment]
Didn't get the chance to merge this PR in time. Let's close it.

**Pull request closed without merging**
