### PR TITLE
[ASStackLayoutSpec] Fix interitem spacing not being reset on new lines and add snapshot tests  #trivial

### LINKED ISSUE #489: Snapshot tests for line spacing of stack layout spec
As a follow up on #472, it would be great to have test cases to capture the behavior of the new line spacing feature and to ensure the bug fixed that PR won't occur again.

### PR DESCRIPTION
**Pull request by nguyenhuy**
Follow up on #472. Closes #489.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/440720b7221d8288e8707e9e4aa3c906/raw/e67f71fba33fa93ad15d1d5a0d1b3cbcce44fad3/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/bf50c713c56e645c35811e6b74cc9c39/raw/8140b737358425e197aba4f671eeb20c8aa66cdf/log.txt)

**Comment by flovouin** [comment]
Oh wow, thanks for this @nguyenhuy, I didn't know you would get on this so quickly.
Sorry for the extra work I put on you!

**Comment by nguyenhuy** [comment]
@flovouin No worries at all! I'm working on improving `ASCollectionGalleryLayoutDelegate` which requires line spacing and figured it's best to have tests now.

And I found a bug :) Please see the fix included in this PR [here](https://github.com/TextureGroup/Texture/pull/491/files#diff-f326c112056bece494def8f931754286R651). The problem is that for the last item that can't fit into an existing line, we include interitem spacing into its stack dimension sum and carry that onto a new line. It then causes another item, which otherwise should be the last item of that line, to be pushed to yet another line (see screenshots below). Fix by resetting interitem spacing when we break to a new line.

Before:
testflexwrapwithitemspacingsbeingresetonnewlines 2x

After:
testflexwrapwithitemspacingsbeingresetonnewlines 2x

**Comment by flovouin** [comment]
Oh I see, nice catch! That was a stupid mistake on my side, sorry about that. :/
Thanks again!

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/b9cafd448791dc42844c5f4f78754f6a/raw/7233aa473b5dc51925f4e12b5716925393ba2a19/log.txt)

**Comment by nguyenhuy** [comment]
I didn't catch it during code review, so it's my fault as well :P

**Comment by nguyenhuy** [comment]
Thanks, @maicki.

**Pull request merged**
