### PR TITLE
Reduce startup time.

### PR DESCRIPTION
**Pull request by dmaclach**
Make global static a function local static. This stops it from being initialized premain and affecting startup time.

### CODE REVIEW

**Comment by maicki** [comment]
I would be interested to get some benchmarks numbers around this area. @dmaclach Did you profile by any chance?

Looking at http://www.modernescpp.com/index.php/thread-safe-initialization-of-a-singleton it seems static vars with block scope is faster as using `std::call_once` what I would compare with `dispatch_once`.

**Comment by maicki** [comment]
I looked a bit more into benchmarking C++ static variables with block scope and dispatch_once initialization. This is a small benchmark script and the results running it three  times are at the end. Pretty interesting and from based on the results we should go with `dispatch_once`:

```
#import <AppKit/AppKit.h>

extern "C" {
  extern uint64_t dispatch_benchmark(size_t count, void (^block)(void));
}

static NSArray *DefaultLinkAttributeNamesMagicStatic() {
  static NSArray *names = @[ NSLinkAttributeName ];
  return names;
}

static NSArray *DefaultLinkAttributeNamesMagicDispatchOnce() {
  static NSArray *names = nil;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    names = @[ NSLinkAttributeName ];
  });
  return names;
}

static void testDefaultLinkAttributeNamesMagicStatic(size_t iterations) {
  uint64_t t = dispatch_benchmark(iterations, ^{
    __unused NSArray *_ = DefaultLinkAttributeNamesMagicStatic();
  });
  NSLog(@"DefaultLinkAttributeNamesMagicStatic Avg. Runtime: %llu ns", t);
}

static void testDefaultLinkAttributeNamesMagicDispatchOnce(size_t iterations) {
  uint64_t t = dispatch_benchmark(iterations, ^{
    __unused NSArray *_ = DefaultLinkAttributeNamesMagicDispatchOnce();
  });
  NSLog(@"DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: %llu ns", t);
}

int main(int argc, const char * argv[]) {
  @autoreleasepool {
    size_t iterations = 100000;

    for (int i = 0; i < 5; i++) {
      testDefaultLinkAttributeNamesMagicStatic(iterations);
    }

    for (int i = 0; i < 5; i++) {
      testDefaultLinkAttributeNamesMagicDispatchOnce(iterations);
    }
  }
  return 0;
}
```

#### Runs:
### 1. Run:
```
2018-12-18 15:38:26.754728+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:38:26.759215+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:38:26.763499+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:38:26.767830+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 42 ns
2018-12-18 15:38:26.772055+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:38:26.775158+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:38:26.778210+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:38:26.781240+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:38:26.784296+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:38:26.787350+0100 StaticInitializerBenchmark[62817:763142] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
Program ended with exit code: 0
```

### 2. Run:
```
2018-12-18 15:41:12.422922+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 40 ns
2018-12-18 15:41:12.427357+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:12.431553+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 40 ns
2018-12-18 15:41:12.435736+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 40 ns
2018-12-18 15:41:12.440016+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:12.443089+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:12.446144+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:12.449175+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:12.452215+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:12.455317+0100 StaticInitializerBenchmark[63262:768527] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
```

### 3. Run:
```
DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:27.896422+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:27.900657+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:27.904917+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:27.909145+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 41 ns
2018-12-18 15:41:27.912189+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:27.915272+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:27.918314+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:27.921354+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
2018-12-18 15:41:27.924386+0100 StaticInitializerBenchmark[63345:769423] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 29 ns
```

**Comment by maicki** [comment]
Also interesting moving this to multithreading access via `displatch_apply`:
```
int main(int argc, const char * argv[]) {
  @autoreleasepool {
    size_t iterations = 10000000;

    dispatch_apply(5, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^(size_t size) {
      testDefaultLinkAttributeNamesMagicStatic(iterations);
    });
//    for (int i = 0; i < 5; i++) {
//      testDefaultLinkAttributeNamesMagicStatic(iterations);
//    }

    dispatch_apply(5, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^(size_t size) {
      testDefaultLinkAttributeNamesMagicDispatchOnce(iterations);
//      testDefaultLinkAttributeNamesMagicStatic(iterations);
    });
//    for (int i = 0; i < 5; i++) {
//      testDefaultLinkAttributeNamesMagicDispatchOnce(iterations);
//    }
  }
  return 0;
}
```

### 1. Run
```
2018-12-18 15:54:00.366062+0100 StaticInitializerBenchmark[65799:799487] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 147 ns
2018-12-18 15:54:20.788231+0100 StaticInitializerBenchmark[65799:799550] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 2189 ns
2018-12-18 15:54:20.888724+0100 StaticInitializerBenchmark[65799:799551] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 2199 ns
2018-12-18 15:54:21.011695+0100 StaticInitializerBenchmark[65799:799552] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 2211 ns
2018-12-18 15:54:21.108568+0100 StaticInitializerBenchmark[65799:799549] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 2221 ns
2018-12-18 15:54:21.813471+0100 StaticInitializerBenchmark[65799:799487] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 69 ns
2018-12-18 15:54:34.741430+0100 StaticInitializerBenchmark[65799:800431] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1362 ns
2018-12-18 15:54:34.781250+0100 StaticInitializerBenchmark[65799:800433] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1366 ns
2018-12-18 15:54:34.802389+0100 StaticInitializerBenchmark[65799:800432] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1368 ns
2018-12-18 15:54:34.804086+0100 StaticInitializerBenchmark[65799:800430] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1368 ns
Program ended with exit code: 0
```

### 2. Run:
```
2018-12-18 15:56:37.261955+0100 StaticInitializerBenchmark[66188:806050] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 164 ns
2018-12-18 15:56:50.403851+0100 StaticInitializerBenchmark[66188:806140] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 1478 ns
2018-12-18 15:56:50.493371+0100 StaticInitializerBenchmark[66188:806138] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 1487 ns
2018-12-18 15:56:50.523936+0100 StaticInitializerBenchmark[66188:806141] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 1490 ns
2018-12-18 15:56:50.625962+0100 StaticInitializerBenchmark[66188:806139] DefaultLinkAttributeNamesMagicStatic Avg. Runtime: 1501 ns
2018-12-18 15:56:52.460112+0100 StaticInitializerBenchmark[66188:806050] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 182 ns
2018-12-18 15:57:03.374937+0100 StaticInitializerBenchmark[66188:806944] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1273 ns
2018-12-18 15:57:03.383686+0100 StaticInitializerBenchmark[66188:806947] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1274 ns
2018-12-18 15:57:03.392869+0100 StaticInitializerBenchmark[66188:806945] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1275 ns
2018-12-18 15:57:03.394173+0100 StaticInitializerBenchmark[66188:806946] DefaultLinkAttributeNamesMagicDispatchOnce Avg. Runtime: 1275 ns
Program ended with exit code: 0
```

**Comment by dmaclach** [comment]
Thanks folks. Moved over to dispatch_once.

**Comment by nguyenhuy** [comment]
Very interesting numbers, thanks for sharing @maicki.

**Comment by dmaclach** [comment]
FWIW 

https://opensource.apple.com/source/libcppabi/libcppabi-26/src/cxa_guard.cxx.auto.html

**Comment by mikezucc** [comment]
cool stuff!

**Comment by dmaclach** [comment]
@maicki can you merge? I do not have privs.

**Pull request merged**
