### PR TITLE
[ASImageNode] Enable .clipsToBounds by default (fix .cornerRadius, GIFs overflow).

### PR DESCRIPTION
**Pull request by appleguy**
We've seen a number of bugs reported over time that .cornerRadius didn't work on
ASNetworkImageNode. This wasn't much of a concern because cornerRadius is very
inefficient anyway, and there are better ways to round corners, but it should
certainly work.

It turns out that clipsToBounds has been off for images, and this ultimately
was behind another issue recently seen where decoded GIFs would spill outside
the bounds area to overlap nearby content.

Although there is some risk of behavior change from this, I think the risk
is fairly small, and in most cases it will probably fix behaviors in a way
that doesn't cause problems for the app.

We should consider if this property should be on for all ASDisplayNodes,
but for now it would be a great step to be confident it's on for all
ASImageNodes.

One of the reports of this issue:
https://github.com/facebookarchive/AsyncDisplayKit/issues/490

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Adlai-Holler** [comment]
Concur with Michael this is a reasonable move, with an assumption that clipsToBounds is pretty fast unless you're masking/rounding corners. But we should document the different default. At first blush I would support generalizing this to ASDisplayNode on that same assumption – having content spill over the bounds should be the exception not the rule.

**Comment by wCodeQ** [comment]
I want to know how to load a GIF Image using ASImageNode,Thanks.

**Comment by appleguy** [comment]
I believe it is necessary to use ASNetworkImageNode. You can also pass
file:/// URLs to it. Make sure you have PINRemoteImage linked.

**Pull request merged**
