### PR TITLE
[WIP][Tests] Fix test failures under iOS 11 #trivial

### PR DESCRIPTION
**Pull request by nguyenhuy**
Reasons for those failures:
- Text rasterization and baseline calculation are a bit different.
- `actionForLayer:forKey:` with `kCAOnOrderIn` as the key is called on sublayers only if the window is visible. Previously it's called as soon as the root view is added to a window.
- Main thread checker complaints about accessing `nextResponder` of a view off main (#342).
- `contentsScale` of a layer that has a corresponding view is automatically loaded by the view to a value appropriate to the screen.
- Taking a snapshot of a view with a clear background results in a completely black image.
- `@available` is enforced by Xcode 9.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextNodeSnapshotTests.m:</p>
<pre><code>//
//  ASTextNodeSnapshotTests.m
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) 2017-present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/3f3ae8a75062dffc26b10a9141df8bc5/raw/ff42495bb4d95884a1bcf7cd8096736b7834d291/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASTextNodeSnapshotTests.m:</p>
<pre><code>//
//  ASTextNodeSnapshotTests.m
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) 2017-present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a705d537c06f94a9edb3d1f4c53a9369/raw/0a397290a256ce0fe19cc17accd8e76e591dd4a5/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/61c522376c2b282f3705197414a0ce46/raw/42df44393e978fb2c09f4332febfbcbc102c40b6/log.txt)

**Comment by Jasdev** [comment]
@nguyenhuy:

> Taking a snapshot of a view with a clear background results in a completely black image.

We've been running into this issue at Peloton too in recording snapshots (even of vanilla view controllers) when targeting iOS 11 (were fine on iOS 10.x). For instance, the navigation bar below will render fine on device/simulator, but will have a random black bar across it (no other `UIAppearance` calls or customizations). Where you able to make any heads way on this issue does this look like a `UIKit` issue?

screen shot 2017-10-18 at 1 15 34 pm

Any help or learnings (cc @appleguy) from your investigation so far would mean a lot!

**Comment by nguyenhuy** [comment]
@jasdev Sorry I didn't answer your question. I unfortunately haven't made any progress in this matter.

**Pull request closed without merging**
