### PR TITLE
Don't add extraneous truncation token during kCTLineTruncationMiddle.

### PR DESCRIPTION
**Pull request by wiseoldduck**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/bfab168bad2b9a0a25cea5f72b58a0cb/raw/b82bf2cbaaa9eb82e2c94bda36b3b32e5d2353c6/log.txt)

**Comment by garrettmoon** [comment]
@wiseoldduck @Adlai-Holler Looks like this broke snapshot tests:

```



ASTextNode2SnapshotTests
  | testTextTruncationModes_ASTextNode2, ((noErrors) is true) failed - Snapshot comparison failed: Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 1.00% from the reference image, FBDiffedImageKey=<UIImage: 0x600000c92ac0>, {375, 667}, FBReferenceImageKey=<UIImage: 0x600000e842e0>, {375, 667}, FBCapturedImageKey=<UIImage: 0x600000c99550>, {375, 667}, NSLocalizedDescription=Images different}
  | /Users/Shared/buildkite/builds/iosf-garrett-vuqKsO4.dyn.pinadmin.com-1/pinterest/texture/Tests/ASTextNode2SnapshotTests.mm:204
  | ```
  | [ASSnapshotTestCase hackilySynchronouslyRecursivelyRenderNode:textNode];
  | ASSnapshotVerifyViewWithTolerance(container, identifier, 0.01);
  | }
  | ```
  |  
  | testTextTruncationModes_ASTextNode2, ((noErrors) is true) failed - Snapshot comparison failed: Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 1.00% from the reference image, FBDiffedImageKey=<UIImage: 0x60800109eaf0>, {375, 667}, FBReferenceImageKey=<UIImage: 0x600000c97020>, {375, 667}, FBCapturedImageKey=<UIImage: 0x608001280e10>, {375, 667}, NSLocalizedDescription=Images different}
  | /Users/Shared/buildkite/builds/iosf-garrett-vuqKsO4.dyn.pinadmin.com-1/pinterest/texture/Tests/ASTextNode2SnapshotTests.mm:204
  | ```
  | [ASSnapshotTestCase hackilySynchronouslyRecursivelyRenderNode:textNode];
  | ASSnapshotVerifyViewWithTolerance(container, identifier, 0.01);
  | }
  | ```
 

```

**Comment by Adlai-Holler** [comment]
Huh, weird that the CI passed. Revert is here #1371

**Comment by wiseoldduck** [comment]
Yes I added the snapshot tests sometime after this PR was created, will need to update them to reflect the non-buggy truncation mode

**Comment by Adlai-Holler** [comment]
Ah got it 👍

**Pull request merged**
