### PR TITLE
Add a recent talk by @smeis at CocoaHeadsNL

### PR DESCRIPTION
**Pull request by nguyenhuy**
Awesome talk, @smeis! Please let me know if you want to add anything. We'll land this PR only with your approval.

### CODE REVIEW

**Comment by nguyenhuy** [comment]
Also, @smeis, let us know if it's ok to add Blendle to our showcase page.

**Comment by smeis** [comment]
Hi @nguyenhuy, thanks for the compliment! Yes you have my approval!

**Comment by smeis** [comment]
And yes we'd love to be on the showcase page!

**Comment by nguyenhuy** [comment]
Great. Thank you, @smeis!

**Pull request merged**
