### PR TITLE
[ASCollectionNode][ASTableNode] Add content inset bridging property

### PR DESCRIPTION
**Pull request by nguyenhuy**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/6489bdeb6319884eeefbc0325a97ef9a/raw/6bf76d8255dac5e1ab9b57fcb79a616b6e5e82da/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/f243c1c91fb04c53035e324f242cde70/raw/d6bc38d6e7d14b6c3a512c408f8b8aa188d28535/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/e326425b07cb59f92dce070383d9ad44/raw/254cb2c6e2f688b2f1b112a8eac3bb6f0ee79d14/log.txt)

**Comment by nguyenhuy** [comment]
Thanks, @maicki!

**Pull request merged**
